inputs:
  http:
    type: http
    host: 0.0.0.0
    port: 10080
    elasticAPI: /elastic
    criblAPI: /cribl
    splunkHecAPI: /services/collector
  splunk:
    type: splunk
    disabled: false
    host: 0.0.0.0
    port: 9997
    tls:
      disabled: true
    ipWhitelistRegex: /.*/
